### ISSUE TITLE
waiting for file to be created.

### ISSUE THREAD

**Issue by alani4837** [antjpcdrogas/chatGPTVoiceDiscBot#2]
Hello and thank you for your development.

I have an issue with running thw bot:

`Not able to read text, try again.
Error: No text to speak
    at new gTTS (/home/user/Desktop/projects/chatGPTVoiceDiscBot/node_modules/gtts/lib/gTTS.js:75:11)
    at saveTextFile (/home/user/Desktop/projects/chatGPTVoiceDiscBot/discordChatGPTVoiceBot.js:84:16)
    at chatgpt (/home/user/Desktop/projects/chatGPTVoiceDiscBot/discordChatGPTVoiceBot.js:149:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
waiting for file to be created.
`
and finishing with file not created. Is there any issue or am I missing something?

**Comment by antjpcdrogas** [comment]
Hello! Thanks for trying out the bot. 

The issue described is fixed in the latest version. Let me know if something is not working as expected.

For context, previously the bot was waiting for file creation using promises. I removed the awaits and switched to callbacks, removing the need for promises to be completed.
Thanks!
